Ajustes workflow eks-setup-dev.

diff --git a/.github/workflows/eks-setup-dev.yml b/.github/workflows/eks-setup-dev.yml
--- a/.github/workflows/eks-setup-dev.yml
+++ b/.github/workflows/eks-setup-dev.yml
@@ -14,6 +14,7 @@ concurrency:
 env:
   AWS_REGION: ${{ secrets.AWS_REGION }}
   CLUSTER_NAME: solventa-dev-eks
+  VPC_NAME: solventa-dev-vpc
   LBC_ROLE_NAME: AWSLoadBalancerControllerIAMRole
   SECRETS_CSI_ROLE_NAME: SecretStoreCSIDriverIAMRole
   CLOUDWATCH_ROLE_NAME: CloudWatchObservabilityIAMRole
@@ -175,23 +176,35 @@ jobs:
 
           aws eks update-kubeconfig --name "$CLUSTER_NAME"
 
-          kubectl logs -f -n kube-system deployment/aws-load-balancer-controller -c aws-load-balancer-controller 
+          # kubectl logs -f -n kube-system deployment/aws-load-balancer-controller -c aws-load-balancer-controller 
 
-          # helm uninstall aws-load-balancer-controller --namespace kube-system || true
-          # kubectl delete serviceaccount aws-load-balancer-controller --namespace kube-system --ignore-not-found=true
+          helm uninstall aws-load-balancer-controller --namespace kube-system || true
+          kubectl delete serviceaccount aws-load-balancer-controller --namespace kube-system --ignore-not-found=true
 
-          # helm repo add eks https://aws.github.io/eks-charts
-          # helm repo update
+          helm repo add eks https://aws.github.io/eks-charts
+          helm repo update
 
-          # helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
-          #   --namespace kube-system \
-          #   --create-namespace \
-          #   --set clusterName="$CLUSTER_NAME" \
-          #   --set enablePodIdentity=true \
-          #   --set serviceAccount.create=true \
-          #   --set serviceAccount.name=aws-load-balancer-controller \
-          #   --wait \
-          #   --timeout 10m
+          VPC_ID=$(aws ec2 describe-vpcs \
+            --filters "Name=tag:Name,Values=${VPC_NAME}" \
+            --query "Vpcs[0].VpcId" \
+            --output text)
+
+          if [ -z "$VPC_ID" ] || [ "$VPC_ID" == "None" ]; then
+              echo "Error: VPC with name '${VPC_NAME}' not found."
+              exit 1
+          fi
+
+          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
+            --namespace kube-system \
+            --create-namespace \
+            --set clusterName="$CLUSTER_NAME" \
+            --set enablePodIdentity=true \
+            --set serviceAccount.create=true \
+            --set serviceAccount.name=aws-load-balancer-controller \
+            --set region=$AWS_REGION \
+            --set vpcId=$VPC_ID \
+            --wait \
+            --timeout 10m
 
       - name: Install AWS Secrets Store CSI Driver Add-on
         shell: bash
